name: Executer des tests e2e avec Cypress

on: [push, workflow_dispatch]

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Execute tests
        run: npx cypress run
      - uses: actions/upload-artifact@v3
        with:
          name: TEST_REPORT
          path: temp/
